config/routes.rb
Rails.application.routes.draw do
  resources :correspondences
  resources :categories
  devise_for :users

  root 'welcome#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/correspondence.rb
class Correspondence < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:descripcion, :dia)
    end
end

app/controllers/correspondences_controller.rb
class CorrespondencesController < ApplicationController
  before_action :set_correspondence, only: [:show, :edit, :update, :destroy]

  # GET /correspondences
  # GET /correspondences.json
  def index
    @correspondences = Correspondence.all
  end

  # GET /correspondences/1
  # GET /correspondences/1.json
  def show
  end

  # GET /correspondences/new
  def new
    @correspondence = Correspondence.new
  end

  # GET /correspondences/1/edit
  def edit
  end

  # POST /correspondences
  # POST /correspondences.json
  def create
    @correspondence = Correspondence.new(correspondence_params)

    respond_to do |format|
      if @correspondence.save
        format.html { redirect_to @correspondence, notice: 'Correspondence was successfully created.' }
        format.json { render :show, status: :created, location: @correspondence }
      else
        format.html { render :new }
        format.json { render json: @correspondence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /correspondences/1
  # PATCH/PUT /correspondences/1.json
  def update
    respond_to do |format|
      if @correspondence.update(correspondence_params)
        format.html { redirect_to @correspondence, notice: 'Correspondence was successfully updated.' }
        format.json { render :show, status: :ok, location: @correspondence }
      else
        format.html { render :edit }
        format.json { render json: @correspondence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /correspondences/1
  # DELETE /correspondences/1.json
  def destroy
    @correspondence.destroy
    respond_to do |format|
      format.html { redirect_to correspondences_url, notice: 'Correspondence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_correspondence
      @correspondence = Correspondence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def correspondence_params
      params.require(:correspondence).permit(:user_id, :category_id, :titulo, :descripcion, :inicio, :fin, :estado)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/correspondences_helper.rb
module CorrespondencesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descripción %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :Numero_de_dias %><br>
    <%= f.number_field :dia %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @category %> |
<%= link_to 'Regresar', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Categorias</h1>

<table class="table">
  <thead>
    <tr class="info">
      <th>Descripción</th>
      <th>Numero de Dias</th>
      <th colspan="3">Opciones</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.descripcion %></td>
        <td><%= category.dia %></td>
        <td><%= link_to 'Mostrar', category %></td>
        <td><%= link_to 'Editar', edit_category_path(category) %></td>
        <td><%= link_to 'Eliminar', category, method: :delete, data: { confirm: '¿Estas seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nueva Categoria', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descripción:</strong>
  <%= @category.descripcion %>
</p>

<p>
  <strong>Numero de dias:</strong>
  <%= @category.dia %>
</p>

<%= link_to 'Editar', edit_category_path(@category) %> |
<%= link_to 'Regresar', categories_path %>

app/views/correspondences/_form.html.erb
<%= form_for(@correspondence) do |f| %>
  <% if @correspondence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@correspondence.errors.count, "error") %> prohibited this correspondence from being saved:</h2>

      <ul>
      <% @correspondence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion %>
  </div>
  <div class="field">
    <%= f.label :inicio %><br>
    <%= f.date_select :inicio %>
  </div>
  <div class="field">
    <%= f.label :fin %><br>
    <%= f.date_select :fin %>
  </div>
  <div class="field">
    <%= f.label :estado %><br>
    <%= f.check_box :estado %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/correspondences/edit.html.erb
<h1>Editing Correspondence</h1>

<%= render 'form' %>

<%= link_to 'Show', @correspondence %> |
<%= link_to 'Back', correspondences_path %>

app/views/correspondences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Correspondences</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Category</th>
      <th>Titulo</th>
      <th>Descripcion</th>
      <th>Inicio</th>
      <th>Fin</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @correspondences.each do |correspondence| %>
      <tr>
        <td><%= correspondence.user %></td>
        <td><%= correspondence.category %></td>
        <td><%= correspondence.titulo %></td>
        <td><%= correspondence.descripcion %></td>
        <td><%= correspondence.inicio %></td>
        <td><%= correspondence.fin %></td>
        <td><%= correspondence.estado %></td>
        <td><%= link_to 'Show', correspondence %></td>
        <td><%= link_to 'Edit', edit_correspondence_path(correspondence) %></td>
        <td><%= link_to 'Destroy', correspondence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Correspondence', new_correspondence_path %>

app/views/correspondences/new.html.erb
<h1>New Correspondence</h1>

<%= render 'form' %>

<%= link_to 'Back', correspondences_path %>

app/views/correspondences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @correspondence.user %>
</p>

<p>
  <strong>Category:</strong>
  <%= @correspondence.category %>
</p>

<p>
  <strong>Titulo:</strong>
  <%= @correspondence.titulo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @correspondence.descripcion %>
</p>

<p>
  <strong>Inicio:</strong>
  <%= @correspondence.inicio %>
</p>

<p>
  <strong>Fin:</strong>
  <%= @correspondence.fin %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @correspondence.estado %>
</p>

<%= link_to 'Edit', edit_correspondence_path(@correspondence) %> |
<%= link_to 'Back', correspondences_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Alcaldia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= image_tag "logo.png", :class =>"img-responsive", :style => "width: 40%;" %>
<br>
<%= render "navegacion/nav"%>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div class="container">
	<%= yield %>
</div>


</body>
</html>

app/views/navegacion/_nav.html.erb
<nav class="navbar navbar-default" role ="navigation">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#acolapsar">
				<span class="sr-only">
					Principal
				</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a href="#" class="navbar-brand">Alcaldia de Fusagasugá</a>
		</div>
		<div class="collapse navbar-collapse" id="acolapsar">
			<ul class="nav navbar-nav">
				<li><a href="#"><span class="glyphicon glyphicon-home"></span> Inicio</a></li>
				<li><a href="#"><span class="glyphicon glyphicon-list-alt"></span> Lista de Derechos de Petición</a></li>
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-option-vertical"></span> Opciones Derechos de Petición<b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li>
							<li><a href="#">Agregar Derecho de Petición</a></li>
							<li><a href="#">Consulta Derecho de Petición</a></li>
						</li>
					</ul>
				</li>
				<li>
					<a href="#"><span class="glyphicon glyphicon-cog"></span> Configuraciones</a>
				</li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<a href="#">Iniciar Sesion</a>
				
			</ul>
		</div>
	</div>
</nav>